# The Deliverfile allows you to store various App Store Connect metadata
# For more information, check out the docs
# https://docs.fastlane.tools/actions/deliver/

app_identifier "org.onionshare.OnionShare"
team_id "127282973"

skip_binary_upload true
skip_app_version_update true
automatic_release true
precheck_include_in_app_purchases false

# Only metadata upload
skip_screenshots true

# Only screenshot upload
#skip_metadata true
#overwrite_screenshots true
